language: go

go:
  - 1.7
  - 1.8
  - 1.6

env:
  - ORM_DRIVER=mysql    ORM_SOURCE="root:@/orm_test?charset=utf8"

before_install:
  - go get github.com/astaxie/beego
  - go get github.com/beego/bee
  - go get golang.org/x/crypto/bcrypt
  - curl https://glide.sh/get | sh

install:
  - glide install

before_script:
  - sh -c "if [ '$ORM_DRIVER' = 'mysql' ]; then mysql -u root -e 'create database posres;'; fi"
script:
  - go build main.go
